apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-dataspace
  template:
    metadata:
      labels:
        app: nginx-dataspace
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: test
spec:
  selector:
    app: nginx-dataspace
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx
  namespace: test
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
spec:
  rules:
    - host: your.domain.org
      http:
        paths:
          - backend:
              service:
                name: nginx
                port:
                  number: 80
            pathType: Prefix
            path: /
  tls:
    - hosts:
        - your.domain.org
      secretName: your.domain.org-cert
